version: "3.8"
services:
  localstack:
    image: localstack/localstack:1.4
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  image-service:
    build: .
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET=montycloud-images
      - DDB_TABLE=Images
    depends_on:
      - localstack
    ports:
      - "8080:8080"
